graphql:
  spqr:
    gui:
      enabled: true

server:
  port: 7777

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.keycloak.issuerUri}
      client:
        registration:
          keycloak:
            client-id: 'app-demo-graphql'
            authorizationGrantType: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: none
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:8080/auth/realms/training
            user-name-attribute: preferred_username

